name: Auto Heal Test Workflow

on:
  push
  pull_request

jobs:
  auto-heal
    runs-on ubuntu-latest

    steps:
      - name Checkout repository
        uses actions/checkout@v4

      - name: Run auto heal
        run echo "Running auto heal"

      - name: Missing pipe
        run:
          echo "This will fail"
